/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TvImport } from './routes/tv'
import { Route as SearchImport } from './routes/search'
import { Route as MovieImport } from './routes/movie'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TvRoute = TvImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const MovieRoute = MovieImport.update({
  id: '/movie',
  path: '/movie',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/movie': {
      id: '/movie'
      path: '/movie'
      fullPath: '/movie'
      preLoaderRoute: typeof MovieImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movie': typeof MovieRoute
  '/search': typeof SearchRoute
  '/tv': typeof TvRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movie': typeof MovieRoute
  '/search': typeof SearchRoute
  '/tv': typeof TvRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/movie': typeof MovieRoute
  '/search': typeof SearchRoute
  '/tv': typeof TvRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/movie' | '/search' | '/tv'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movie' | '/search' | '/tv'
  id: '__root__' | '/' | '/movie' | '/search' | '/tv'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovieRoute: typeof MovieRoute
  SearchRoute: typeof SearchRoute
  TvRoute: typeof TvRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovieRoute: MovieRoute,
  SearchRoute: SearchRoute,
  TvRoute: TvRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/movie",
        "/search",
        "/tv"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/movie": {
      "filePath": "movie.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/tv": {
      "filePath": "tv.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
